name: Gradle Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-quilt-mappings:
    strategy:
      matrix:
        java: [17, 19]
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'QuiltMC/quilt-mappings'
          ref: '23w17a'
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew publishToMavenLocal --stacktrace
      - name: Build artifacts
        if: ${{ matrix.java == 17 }}
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: Quilt Mappings Artifacts
          path: ~/.m2/repository/org/quiltmc/quilt-mappings
          retention-days: 1

  build:
    strategy:
      matrix:
        java: [ 17, 19 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - uses: actions/upload-artifact@v2
        with:
          name: Quilt Mappings Artifacts
          path: ~/.m2/repository/org/quiltmc/quilt-mappings

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --parallel --stacktrace
          cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/1.') && !startsWith(github.ref, 'refs/heads/dev/') && !startsWith(github.ref, 'refs/tags/v') }}

      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./build/libs/
